### ISSUE TITLE
请问新的vocab啥时候能出来呢？目前的voab和bert-base-chinese基本上无区别。

### ISSUE THREAD

**Issue by gongel** [hsc748NLP/SikuBERT-for-digital-humanities-and-classical-Chinese-information-processing#2]

**Comment by SIKU-BERT** [comment]
您好，目前改良词表的实验已经到测试截断，预计9月中旬将发布新的版本。

**Comment by SIKU-BERT** [comment]
您好，目前改良词表的实验已经到了测试阶段了，预计9月中旬将发布新的版本。

**Comment by SIKU-BERT** [comment]
您好，目前具有《四库全书》原生词的词表的新模型已经发布，huggingface上的模型以同步更新，已经可以从新的百度云链接或huggingface下载了

**Comment by SIKU-BERT** [comment]
> _No description provided._

您好，目前具有《四库全书》原生词的词表的新模型已经发布，huggingface上的模型已同步更新，用户可以从新的百度云链接下载或以之前相同的代码调用huggingface上的模型。感谢您的关注。
